# Generated by Django 5.0.4 on 2024-08-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
