# Generated by Django 5.0.4 on 2024-08-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_workingday_doctorprofile_working_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='working_days',
        ),
        migrations.DeleteModel(
            name='WorkingDay',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
