# Generated by Django 5.0.4 on 2024-08-29 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('working_day', models.CharField(max_length=20)),
                ('appointment_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctorprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
